#!/bin/bash

echo -e 'Content-type: text/html; \r\n\r\n'

cat << ENDHTML

<html>
	<META HTTP-EQUIV="REFRESH" CONTENT="60">
	<body>
		<h1> Hello World!</h1>
	<pre>
	Your IP address: $HTTP_X_REAL_IP
	Your Port: $HTTP_X_REAL_PORT
	Nginx Version: $HTTP_NGINX_VERSION
	$(python3  hello.py >  /var/vhosts/bonet1/data/test)
	$(python3 data_test.py)
	$(./test_data_time.sh)
	</pre>
	</body>
</html>
ENDHTML
