#!/bin/bash

echo -e 'Content-type: text/html; \r\n\r\n'

cat << ENDHTML

<html>
	<META HTTP-EQUIV="REFRESH" CONTENT="60">
	<style type="text/css">
	table {
		border-collapse: collapse;
	}
	table th,
	table td {
		padding: 0 3px;
	}
	table.brd th,
	table.brd td {
		border: 1px solid #000;
	}
	</style>
	<body>
	<p><strong>Your IP address</strong>: $HTTP_X_REAL_IP</p> 
	<p><strong>Your Port</strong>: $HTTP_X_REAL_PORT </p> 
	<p><strong> Nginx Version</strong>: $HTTP_NGINX_VERSION </p>
	$(./test_data_time.sh)

	</body>
</html>
ENDHTML
